drop table if exists temp_privileges;

create table temp_privileges (
    c_what varchar(100),
    c_groups varchar(100),
    c_action_title varchar(100),
    c_granted_on varchar(100),
    c_table varchar(100),
    primary key (c_what, c_groups, c_action_title, c_granted_on, c_table)
) type=MyISAM;

insert into temp_privileges
    (c_what, c_groups, c_action_title, c_granted_on, c_table)
values
    ('group',       2,       'write',             'global',       '[_]member'),
    ('group',       2,       'list_all',          'table',        '[_]action'),
    ('group',       2,       'list_all',          'table',        '[_]expense'),
    ('group',       2,       'list_all',          'table',        '[_]expense_report'),
    ('group',       2,       'list_all',          'table',        '[_]item'),
    ('group',       2,       'list_all',          'table',        '[_]report'),
    ('group',       2,       'view_history',      'global',       '[_]member'),
    ('group',       2,       'choose_activities', 'global',       '[_]location'),
    ('group',       2,       'view_report',       'global',       '[_]adventure'),
    ('group',       2,       'chgrp_secondary',   'global',       '[_]member'),
    ('group',       2,       'execute',           'object',       '[_]report'),
    ('group',       2,       'list_all',          'table',        '[_]checkout'),
    ('group',       2,       'accept',            'global',       '[_]checkout'),
    ('group',       2,       'check_in',          'global',       '[_]checkout'),
    ('group',       2,       'list_all',          'table',        '[_]checkout_item'),
    ('group',       2,       'list_all',          'table',        '[_]checkout_gear'),
    ('group',       2,       'create',            'table',        '[_]checkout'),
    ('group',       2,       'create',            'table',        '[_]checkout_item'),
    ('group',       2,       'create',            'table',        '[_]checkout_gear'),
    ('group',       4,       'list_all',          'table',        '[_]expense_report'),
    ('group',       4,       'list_all',          'table',        '[_]expense'),
    ('group',       4,       'list_all',          'table',        '[_]transaction'),
    ('group',       4,       'create',            'table',        '[_]expense_submission'),
    ('group',       4,       'list_all',          'table',        '[_]expense_submission'),
    ('group',       4,       'list_owned_by',     'table',        '[_]expense_submission'),
    ('group',       4,       'list_owned_by',     'table',        '[_]expense_report'),
    ('group',       4,       'view_notes',        'global',       '[_]expense_report'),
    ('group',       4,       'accept',            'global',       '[_]expense_report'),
    ('group',       4,       'accept',            'global',       '[_]expense_submission'),
    ('group',       4,       'submit',            'global',       '[_]expense_submission'),
    ('group',       8,       'read',              'global',       '[_]absence'),
    ('group',       8,       'list_all',          'table',        '[_]report'),
    ('group',       8,       'list_owned_by',     'table',        '[_]adventure'),
    ('group',       8,       'list_owned_by',     'table',        '[_]expense_report'),
    ('group',       8,       'create',            'table',        '[_]adventure'),
    ('group',       8,       'create',            'table',        '[_]expense'),
    ('group',       8,       'create',            'table',        '[_]expense_report'),
    ('group',       8,       'create',            'table',        '[_]location'),
    ('group',       8,       'create',            'table',        '[_]question'),
    ('group',       8,       'choose_activities', 'global',       '[_]location'),
    ('group',       8,       'view_absences',     'global',       '[_]member'),
    ('group',       8,       'view_waitlist',     'global',       '[_]member'),
    ('group',       16,      'list_all',          'table',        '[_]condition'),
    ('group',       16,      'list_all',          'table',        '[_]item'),
    ('group',       16,      'list_all',          'table',        '[_]item_type'),
    ('group',       16,      'list_all',          'table',        '[_]item_category'),
    ('group',       16,      'list_all',          'table',        '[_]checkout'),
    ('group',       16,      'accept',            'global',       '[_]checkout'),
    ('group',       16,      'check_in',          'global',       '[_]checkout'),
    ('group',       16,      'list_all',          'table',        '[_]checkout_item'),
    ('group',       16,      'list_all',          'table',        '[_]checkout_gear'),
    ('group',       16,      'create',            'table',        '[_]condition'),
    ('group',       16,      'create',            'table',        '[_]item'),
    ('group',       16,      'create',            'table',        '[_]item_type'),
    ('group',       16,      'create',            'table',        '[_]item_category'),
    ('group',       16,      'create',            'table',        '[_]checkout'),
    ('group',       16,      'create',            'table',        '[_]checkout_item'),
    ('group',       16,      'create',            'table',        '[_]checkout_gear'),
    ('group',       16,      'copy',              'global',       '[_]item'),
    ('group',       16,      'edit_features',     'global',       '[_]item'),
    ('group',       16,      'edit_features',     'global',       '[_]item_type'),
    ('group',       16,      'view_notes',        'global',       '[_]item'),
    ('group',       32,      'list_all',          'table',        '[_]activity'),
    ('group',       32,      'list_all',          'table',        '[_]adventure'),
    ('group',       32,      'list_all',          'table',        '[_]classified_ad'),
    ('group',       32,      'list_all',          'table',        '[_]location'),
    ('group',       32,      'list_all',          'table',        '[_]member'),
    ('group',       32,      'list_all',          'table',        '[_]item'),
    ('group',       32,      'list_owned_by',     'table',        '[_]address'),
    ('group',       32,      'list_owned_by',     'table',        '[_]chat'),
    ('group',       32,      'list_owned_by',     'table',        '[_]classified_ad'),
    ('group',       32,      'list_owned_by',     'table',        '[_]phone_number'),
    ('group',       32,      'list_owned_by',     'table',        '[_]subscription'),
    ('group',       32,      'view_history',      'self',         '[_]member'),
    ('group',       32,      'view_history',      'global',       '[_]item'),
    ('group',       32,      'create',            'table',        '[_]address'),
    ('group',       32,      'create',            'table',        '[_]answer'),
    ('group',       32,      'create',            'table',        '[_]attendee'),
    ('group',       32,      'create',            'table',        '[_]chat'),
    ('group',       32,      'create',            'table',        '[_]classified_ad'),
    ('group',       32,      'create',            'table',        '[_]interest'),
    ('group',       32,      'create',            'table',        '[_]phone_number'),
    ('group',       32,      'join',              'global',       '[_]adventure'),
    ('group',       32,      'withdraw',          'global',       '[_]adventure'),
    ('group',       32,      'choose_activities', 'self',         '[_]member'),
    ('group',       32,      'change_password',   'self',         '[_]member'),
    ('group',       32,      'view_waitlist',     'global',       '[_]adventure'),
    ('group',       32,      'comment',           'global',       '[_]adventure'),
    ('group',       32,      'optout',            'self',         '[_]member'),
    ('group',       128,     'su',                'global',       '[_]member'),
    ('group',       256,     'activate',          'global',       '[_]membership'),
    ('group',       256,     'list_all',          'table',        '[_]membership'),
    ('owner',       0,       'activate',          'global',       '[_]adventure'),
    ('owner',       0,       'deactivate',        'global',       '[_]adventure'),
    ('owner',       0,       'deactivate',        'global',       '[_]classified_ad'),
    ('owner',       0,       'edit_questions',    'global',       '[_]adventure'),
    ('owner',       0,       'choose_activities', 'global',       '[_]adventure'),
    ('owner',       0,       'view_report',       'global',       '[_]adventure'),
    ('owner',       0,       'announce',          'global',       '[_]adventure'),
    ('owner',       0,       'email_attendees',   'global',       '[_]adventure'),
    ('owner',       0,       'view_answers',      'global',       '[_]attendee'),
    ('owner',       0,       'unsubscribe',       'global',       '[_]subscription'),
    ('owner',       0,       'submit',            'global',       '[_]expense_report'),
    ('owner_group', 0,       'join',              'global',       '[_]attendee'),
    ('owner_group', 0,       'copy',              'global',       '[_]question'),
    ('owner_group', 0,       'withdraw',          'global',       '[_]attendee'),
    ('owner_group', 0,       'waitlist',          'global',       '[_]attendee'),
    ('owner_group', 0,       'mark_absent',       'global',       '[_]attendee'),
    ('owner_group', 0,       'view_answers',      'global',       '[_]attendee');

-- Only delete non-object-level privileges.  This will make sure user
-- customizations are not wiped out.  Any non-object-level customized
-- privileges ought to be in this file.
delete from [_]privilege where c_related_uid = 0;

insert into [_]privilege
    (c_owner, c_created_date, c_what_granted_to, c_who_granted_to, c_action,
     c_what_relates_to, c_related_table, c_related_uid)
    select
        1,
        now(),
        c_what,
        c_groups,
        c_action_title,
        c_granted_on,
        c_table,
        0 -- These are not object-level privileges so this argument is ignored.
    from temp_privileges;

drop table temp_privileges;
