#!/bin/bash
egrep -rho "function &?([a-zA-Z]+)\(" * | sort | uniq | sed -e "s/&\|function \|(//g" | sort | uniq > defined
egrep -rho "(->|:{2})([a-zA-Z]+)\(" * | sort | uniq | sed -e "s/->\|::\|(//g" | sort | uniq > called
